mergeable:
  pull_requests:
    label:
      and:
        - must_exclude:
            regex: '^disposition/DO NOT MERGE'
            message: 'Pull request marked not mergeable'
        - or:
          - and:
            - must_include:
                regex: 'release notes:\s?yes'
                message: 'Please include release notes: yes'
            - must_include:
                regex: '^(c#|c\+\+|cleanup|conformance tests|integration|java|javascript|go|objective-c|php|python|ruby)'
                message: 'Please include at a language label (e.g., c++, java, python) or a label (cleanup, conformance tests, integration) on a line by itself in the commit comment.'
          - must_include:
              regex: 'release notes:\s?no'
              message: 'Please include release notes: no'
