platform:
  - Win64

configuration:
  - Debug

environment:
  matrix:
    - language: cpp
      image: Visual Studio 2015
      generator: Visual Studio 14 Win64
      BUILD_DLL: ON
      UNICODE: ON

    - language: cpp
      image: Visual Studio 2017
      generator: Visual Studio 15 Win64
      BUILD_DLL: ON
      UNICODE: ON

    - language: csharp
      image: Visual Studio 2017

# Our build scripts run tests automatically; we don't want AppVeyor
# to try to detect them itself.
test: off

install:
  - git submodule update --init --recursive

build_script:
  - CALL appveyor.bat

skip_commits:
  message: /.*\[skip appveyor\].*/
