name: C++ Bazel

on:
  workflow_call:
    secrets:
      GAR_SERVICE_ACCOUNT:
        required: true

jobs:
  run:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        include:
          - { name: "Optimized", config: "opt" }
          #- { name: "Debug", config: "dbg" }
          #- { name: "ASAN", config: "asan" }
          #- { name: "MSAN", config: "kokoro-msan" }
          #- { name: "TSAN", config: "tsan" }
          #- { name: "UBSAN", config: "ubsan" }
    name: ${{ matrix.name }}
    uses: ./.github/workflows/docker_bazel.yml
    with:
      name: ${{ matrix.name }}
      image: us-docker.pkg.dev/protobuf-build/containers/test/linux/sanitize@sha256:dbd2f15fb69734d72c3fd10cb819bbe2ce4890acf49e9a2f9403983fe48e8807
      flags: --distinct_host_configuration=false --config=${{ matrix.config }}
      targets: //pkg/... //src/... @com_google_protobuf_examples//...
      cache: cpp_bazel/${{ matrix.name }}
    secrets: inherit
