name: C++ Bazel Tests

on:
  push:
    branches:
      - gha
  pull_request:
    branches:
      - gha

jobs:
  approve: # First step
    runs-on: ubuntu-latest

    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  run:
    needs: [approve]
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        include:
          - { name: "Optimized", config: "opt" }
          - { name: "Debug", config: "dbg" }
          - { name: "ASAN", config: "asan" }
          - { name: "MSAN", config: "kokoro-msan" }
          - { name: "TSAN", config: "tsan" }
          - { name: "UBSAN", config: "ubsan" }
          - { name: "Opt", config: "opt" }
    name: ${{ matrix.name }}
    uses: ./.github/workflows/docker_run.yml
    with:
      environment: test-docker
      image: us-docker.pkg.dev/protobuf-build/containers/test/linux/sanitize@sha256:dbd2f15fb69734d72c3fd10cb819bbe2ce4890acf49e9a2f9403983fe48e8807
      run: test --distinct_host_configuration=false --config=${{ matrix.config }} //pkg/... //src/... @com_google_protobuf_examples//...
      cache: cpp_bazel/${{ matrix.name }}
    secrets:
      GAR_SERVICE_ACCOUNT: ${{secrets.GAR_SERVICE_ACCOUNT}}
