name: C++ Bazel Tests

on:
  push:
    branches:
      - gha
  pull_request_target:
    branches:
      - gha

jobs:
  approve: # First step
    runs-on: ubuntu-latest

    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.

  setup:
    needs: [approve]
    uses: ./.github/workflows/docker_setup.yml
    with:
      environment: test-docker
    secrets:
      GAR_SERVICE_ACCOUNT: ${{secrets.GAR_SERVICE_ACCOUNT}}

  build: # Second step
    runs-on: ubuntu-latest

    needs: [approve, setup] # Require the first step to finish
    env:
      DOCKER_IMAGE: us-docker.pkg.dev/protobuf-build/containers/test/linux/sanitize@sha256:dbd2f15fb69734d72c3fd10cb819bbe2ce4890acf49e9a2f9403983fe48e8807
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker Image
        run: docker pull $DOCKER_IMAGE
      - name: Test
        run: docker system prune && cd ${{ github.workspace }} && docker run -e GOOGLE_APPLICATION_CREDENTIALS=/workspace/$(basename $GOOGLE_APPLICATION_CREDENTIALS) -v$PWD:/workspace $DOCKER_IMAGE test $BAZEL_CACHE //src/...
