name: Tests

on:
  # postsubmit
  push:
    branches:
      - gha

  # Safe presubmit
  pull_request:
    branches:
      - gha

jobs:
  run:
    name: Tests
    # For push an in-repo pull requests, we have access to secret and the code
    # can be fully trusted. Otherwise, rely on the unsafe test runner to kick
    # off tests.
    if: <
      ${{
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name == 'protocolbuffers/protobuf'
      }}
    uses: ./.github/workflows/run_all_tests.yml
    with:
      environment: test-docker
    secrets:
      GAR_SERVICE_ACCOUNT: ${{secrets.GAR_SERVICE_ACCOUNT}}

