name: C++ Tests

on:
  workflow_call:
    inputs:
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string

permissions:
  contents: read

jobs:
  non-linux:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        index: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
        include:
          - name: Repro
            os: windows-latest
            cache_key: windows-2022-2
            bazel: run //src/google/protobuf/compiler:repro
    name: ${{ matrix.name }} ${{ matrix.index }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout pending changes
        uses: protocolbuffers/protobuf-ci/checkout@v3
        with:
          ref: ${{ inputs.safe-checkout }}
      - name: Run tests
        uses: protocolbuffers/protobuf-ci/bazel@v3
        with:
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel: ${{ matrix.bazel }} -s -c opt
          bazel-cache: msvc_crash-${{ matrix.index }}
          version: ${{ matrix.bazel_version || '6.3.0' }}
